import fs from 'node:fs';
import path from 'node:path';

function extractColorValue(colorStr) {
  const hexMatch = colorStr.match(/#([0-9a-fA-F]{3,6})/);
  return hexMatch ? hexMatch[0] : colorStr;
}

export function generate(visual, outputPath) {
  const { typography, colors, radius } = visual;
  
  let cssLines = [];
  
  if (typography) {
    if (typography.baseFontSize) cssLines.push(`  --font-base: ${typography.baseFontSize};`);
    if (typography.smallFontSize) cssLines.push(`  --font-sm: ${typography.smallFontSize};`);
    if (typography.heading1) cssLines.push(`  --font-h1: ${typography.heading1};`);
  }
  
  if (colors) {
    if (colors.primary) cssLines.push(`  --primary: ${extractColorValue(colors.primary)};`);
    if (colors.secondary) cssLines.push(`  --secondary: ${extractColorValue(colors.secondary)};`);
    if (colors.background) cssLines.push(`  --background: ${extractColorValue(colors.background)};`);
  }

  if (radius) {
    if (radius.base) cssLines.push(`  --radius: ${radius.base};`);
  }

  // Use comment markers to safely replace this block on subsequent runs
  const block = `/* DOCSKIT-TOKENS-START */\n/* Auto-generated by Docskit - Do not edit manually */\n@layer base {\n  :root {\n${cssLines.map(line => `  ${line}`).join('\n')}\n  }\n}\n/* DOCSKIT-TOKENS-END */`;
  
  let existingContent = '';
  if (fs.existsSync(outputPath)) {
    existingContent = fs.readFileSync(outputPath, 'utf8');
  }

  const startMarker = '/* DOCSKIT-TOKENS-START */';
  const endMarker = '/* DOCSKIT-TOKENS-END */';

  if (existingContent.includes(startMarker) && existingContent.includes(endMarker)) {
    // Replace the existing docskit block without touching the rest of the file
    const escapedStart = startMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const escapedEnd = endMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regexObj = new RegExp(`${escapedStart}[\\s\\S]*?${escapedEnd}`);
    
    existingContent = existingContent.replace(regexObj, block);
  } else {
    // First time running: append to the bottom of the file
    existingContent += `\n\n${block}\n`;
  }
  
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, existingContent);
  return true;
}
